# Generated by Django 4.1 on 2022-08-19 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gamme', '0001_initial'),
        ('Produit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='gamme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Gamme.gamme'),
        ),
    ]
