# Generated by Django 4.1 on 2022-08-19 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gamme', '0001_initial'),
        ('Produit', '0002_produit_gamme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='gamme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gamme.gamme'),
        ),
    ]
