# Generated by Django 4.1 on 2022-08-22 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Commande', '0006_remove_commande_produit'),
        ('Produit', '0003_alter_produit_gamme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produit',
        ),
    ]
