# Generated by Django 4.1 on 2022-08-22 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Gamme', '0003_initial'),
        ('Produit', '0004_delete_produit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('prix', models.FloatField(default=0.0)),
                ('quantite', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='produits')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('gamme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gamme.gamme')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
