# Generated by Django 4.1 on 2022-09-07 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produit', '0006_remove_produit_quantite_remove_produit_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produit',
        ),
    ]
