# Generated by Django 4.1 on 2022-09-07 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produit', '0008_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produit',
        ),
    ]
