# Generated by Django 4.1 on 2022-08-22 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produit', '0004_delete_produit'),
        ('Gamme', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gamme',
        ),
    ]
