# Generated by Django 4.1 on 2022-08-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Gamme', '0002_delete_gamme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gamme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('produits', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
