# Generated by Django 4.1 on 2022-08-26 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gamme', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamme',
            name='produits',
        ),
    ]
