# Generated by Django 4.1 on 2022-09-01 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mediatheque', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='image',
            new_name='photo',
        ),
    ]
