# Generated by Django 4.1 on 2022-09-01 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mediatheque', '0002_rename_image_photo_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
