# Generated by Django 4.1 on 2022-09-02 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mediatheque', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='description',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='evenement',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='video',
            name='description',
        ),
        migrations.RemoveField(
            model_name='video',
            name='evenement',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video',
        ),
    ]
