# Generated by Django 4.1 on 2022-09-02 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mediatheque', '0005_remove_photo_description_remove_photo_evenement_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
