# Generated by Django 4.1 on 2022-09-09 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Partenaire', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Partenaire',
        ),
    ]
